### ISSUE TITLE
prtClassRasmusbergpalmDeepLearningNn broken?

### ISSUE THREAD

**Issue by samkeene** [covartech/PRT#15]
Recently updated, tried:

  ds = prtDataGenMnist;
  nn = prtClassRasmusbergpalmDeepLearningNn + prtDecisionMap;
  yOut = nn.kfolds(ds,2);

Eventually got this error:

epoch 100/100. Took 0.47235 seconds. Mean squared error on training set is 0.26585
??? Reference to non-existent field 'b'.

Error in ==>
prtClassRasmusbergpalmDeepLearningNn>prtClassRasmusbergpalmDeepLearningNn.runAction
at 74
            tempY = zeros(size(dataSet.X,1),size(self.nn.b{end},1));

Error in ==> prtAction>prtAction.runActionOnTrainingData at 570
            dsOut = runAction(self, dsIn);

Error in ==> prtAction>prtAction.runOnTrainingData at 182
            dsOut = runActionOnTrainingData(self, dsOut);

Error in ==> prtAlgorithm>prtAlgorithm.trainAction at 309
                    input{topoOrder(i)} =
                    runOnTrainingData(Obj.actionCell{topoOrder(i-1)},currentInput);
                    
Error in ==> prtAction>prtAction.train at 217
            self = trainAction(self, ds);

Error in ==> prtAction>prtAction.crossValidate at 359
				trainedAction = self.train(trainDs);

Error in ==> prtAction>prtAction.kfolds at 431
            [outputs{:}] = self.crossValidate(ds,keys);
 
>>

**Comment by patrickkwang** [comment]
This classifier no longer exists in the PRT. In fact, the associated toolbox is deprecated: https://github.com/rasmusbergpalm/DeepLearnToolbox

Problem solved!
