### ISSUE TITLE
Undefined function 'subDir' for input arguments of type 'char'

### ISSUE THREAD

**Issue by lyzhangjm** [covartech/PRT#31]
Hi, when I run torrione_ExampleCoatesNg_Kmeans_Mscorid,  The error information is:

Undefined function 'subDir' for input arguments of type 'char'.
Error in prtDataGenMsrcorid (line 103)
    fList = subDir(cDir,'*.jpg');
Error in torrione_ExampleCoatesNg_Kmeans_Mscorid (line 48)
ds = prtDataGenMsrcorid; 

 My matlab version is 2012a. 
  I don't konw why.
 Thank you。

**Comment by kennethmorton** [comment]
Hi Sorry about this. As a quick fix, please change that to call prtUtilSubDir() instead.

fList = prtUtilSubDir(cDir,'*.jpg');

We will push the changes to the repository soon.

Kenny

**Comment by lyzhangjm** [comment]
thank you, but there are error when using prtUtilSubDir:
    No appropriate method, property, or field addParameter for class inputParser.
Error in prtUtilSubDir (line 46)
p.addParameter('dirMatch','*');
Error in prtDataGenMsrcorid (line 104)
    fList = prtUtilSubDir(cDir,'*.jpg');
Error in torrione_ExampleCoatesNg_Kmeans_Mscorid (line 48)
ds = prtDataGenMsrcorid;

**Comment by peterTorrione** [comment]
Hi,

This is a MATLAB version issue - unfortunately they changed the calling syntax for inputParser in a recent version of MATLAB.

Can you either:

1) Update your MATLAB to 2014

or

2) Replace any calls to addParameter with addParamValue... sorry for the confusion...

Thanks!
-Pete
