### ISSUE TITLE
proposal

### ISSUE THREAD

**Issue by peterTorrione** [covartech/PRT#4]
Enable retainFeatures and retainClasses to take cell arrays of feature Names, or cell Names.  

e.g.

ds = ds.retainClasses({'explosive','inert'});

Can regexp work?

ds = ds.retainClasses({'explosive_','inert_'});  ?

(Maybe for retainObservations, too?)

**Comment by patrickkwang** [comment]
@peterTorrione did this for classes in June, 2012: 92c6835e6d9a62883e8facb4c4c97519cf995870, and for features in March, 2014: a46373391b32bf33df3ffc269b133f5a42831535
I did this just now for observations: 870926cd98d78b6fa4930e40bc27aefb568f0372
