### ISSUE TITLE
Building MEX Files

### ISSUE THREAD

**Issue by msmama** [covartech/PRT#41]
As per your instruction I have done the modification of the following three files
1. C:\Users\Administrator\Documents\MATLAB\PRT-master\doc\prtDoc.m
2. C:\Users\Administrator\Documents\MATLAB\PRT-master\engine\dataset\prtDataSetClass.m
3. C:\Users\Administrator\Documents\MATLAB\PRT-master\util\prtSetup.m
>>prtSetup
 successfully return the matlab prompt
>>mex -setup
Error
---------------------
>> mex -setup
MEX configured to use 'lcc-win32' for C language compilation.
Warning: The MATLAB C and Fortran API has changed to support MATLAB
	 variables with more than 2^32-1 elements. In the near future
	 you will be required to update your code to utilize the
	 new API. You can find more information about this at:
	 http://www.mathworks.com/help/matlab/matlab_external/upgrading-mex-files-to-use-64-bit-api.html.

To choose a different language, select one from the following:
 mex -setup C++ 
 mex -setup FORTRAN
--------------------------------
However in my system  following are already installed 
Control Panel\Programs\Programs and Features

Microsoft .NEt Framework 4 Client Profile
Microsoft .NEt Framework 4 Extended
Microsoft Visual C++ 2005 Redistribution
Microsoft Visual C++ 2008 Express Edition-ENU
Microsoft Visual C++ 2008 Redistributable-x86 9.0.30729.17
Microsoft Visual C++ 2008 Redistributable-x86 9.0.30729.6161
Microsoft Visual C++ 2010 x86 Redistributable (x86) 10.0.30319
Microsoft Visual C++ 2012  Redistributable (x86) 11.0.60610

I need to use the classification techniques of PRT Toolbox. Is it necessary to set "Building MEX Files"  
Please reply what to do

Regards

**Comment by kennethmorton** [comment]
I am not really sure what your question is but it seems like you are having running prtSetupMex

prtSetupMex builds a few of the mex functions shipped with the PRT. The PRT ships with compiled mex for most computer architectures. So, unless you have a strange architecture, you probably don't need to run prtSetupMex. Just start using the PRT and if you run in to issues let us know.
