### ISSUE TITLE
sine activation function Kernel Set 

### ISSUE THREAD

**Issue by aditiegarg** [covartech/PRT#43]
I was trying to use sine activation function as kernel for rvm classification. I cant find it. Can someone please help?

**Comment by covartech** [comment]
Hi,

By default there is no SIN kernel in the PRT, but it should be possible to implement one.  How exactly to do that depends on what you want.   If you want to do sparse fourier analysis, you can get started by overloading something like prtKernelDirect or prtKernelDc.  The parameter of the prtKernelSin should probably be the frequency of the sinusoid and the phase offset.  The Kernels are pretty sparsely documented however, so you're entering a bit of a weird world.  Take a look at prtKernelDc and prtKernelDirect for examples.  Good luck.
