### ISSUE TITLE
prtScoreConfusionMatrix breaks after latest pull

### ISSUE THREAD

**Issue by dimapitt** [covartech/PRT#47]
Hey there!

I was getting an error using the prtScoreConfusionMatrix after the latest pull

`132: prtUtilPlotConfusionMatrix(confusionMat,guessClassNames,truthClassNames);`

I noticed that prtUtilPlotConfusionMatrix should be prtPlotUtilConfusionMatrix. Looks like the name of the function was changed recently

Thanks!

**Comment by patrickkwang** [comment]
This has been fixed on the devel branch: 2192e72dd62792b2bda9352956b887bfe23d160c
