### ISSUE TITLE
Is it possible to set one data set as a training set and another data set as a testing set in classification?

### ISSUE THREAD

**Issue by Laylan** [covartech/PRT#56]
Hi, I was wondering if it is possible to set one data set as a training set and another data set as a testing set. It is important for me to have this data sets as a separate sets for my project. Anyone could help me? And sorry for my bad English....

**Comment by patrickkwang** [comment]
Yes. Simply construct two datasets:
```
dsTrain = prtDataSetClass(X1,y1); % size(X1)=[N,D], size(y1)=[N,1]
dsTest = prtDataSetClass(X2,y2);
```
Then train and test your classifier as follows:
```
cls = prtClassFld; % or your favorite classifier
cls_trained = cls.train(dsTrain);
results = cls_trained.run(dsTest);
prtScoreRoc(results)
```
