### ISSUE TITLE
prtUtilSumExp with no inputs causes seg fault

### ISSUE THREAD

**Issue by peterTorrione** [covartech/PRT#60]
Yuck

<pre>
>> prtUtilSumExp
------------------------------------------------------------------------
          Access violation detected at Thu Nov 09 09:43:26 2017
------------------------------------------------------------------------
....
</pre>

That's grody.

**Comment by kennethmorton** [comment]
Stole this from Patrick. Done in 2e361cb3b81bb82637343eb37dd85f555605dbab
