### ISSUE TITLE
PRT Document Update

### ISSUE THREAD

**Issue by jonioni** [covartech/PRT#64]
Some of the code in the PRT documents doesn't work when using MATLAB online. The PRT package was installed through the online add-on market.

**Comment by peterTorrione** [comment]
Hi Jon,

Can you give an example of what you are trying to do, what tutorial you are looking at, and what goes wrong?

**Comment by peterTorrione** [comment]
Also, whether the issue happens only in MATLAB online, or in desktop MATLAB?  I'm not sure we developed the PRT to be MATLAB Online friendly

**Comment by jonioni** [comment]
Thank you for your attention.

For "[Quick Start](http://covartech.github.io/prtdoc/prtDocQuickStart.html)":

- Command: `dataSet = prtDataSetClass(x,y);`
    - Error:
        ```
        Error using prtOptionsGetFactory (line 21)
        Invalid default value for property 'plotOptions' in class 'prtDataSetClass':
        Package prtOptions was not found on path
        ```
- Command: `fld = prtClassFld;`
    - Error:
        ```
        Undefined function or variable 'prtClassFld'.
        ```

For "[Getting Started Examples](http://covartech.github.io/prtdoc/prtDocGettingStartedExamples.html)":

- Command: `dataSet = prtDataGenUnimodal;` and `dataSet = prtDataGenIris;`
    - Error:
        ```
        Undefined function or variable 'prtDataGenUnimodal'.
        Undefined function or variable 'prtDataGenIris'.
        ```
- Command: `knnClassifier = prtClassKnn;`
    - Error:
        ```
        Undefined function or variable 'prtClassKnn'.
        ```

I installed "Pattern Recognition Toolbox" through the online add-on market.

**Comment by jonioni** [comment]
Still unable to run.

The PRT directory seems different:

![image](https://user-images.githubusercontent.com/31494475/35456061-46651cb8-02a2-11e8-85ae-d3613c18f67f.png)

**Comment by peterTorrione** [comment]
No problem!  I still dont fully understand what was happening!  We didnt design for MATLAB Online, so, to be frank, I am amazed this works at all.  

Please let us know if you have other issues on the GITHUB.  We dont follow the web-page for the MATLAB Add-On
