### ISSUE TITLE
Proposal - All clustering objects sort their cluster indices by increasing first dim

### ISSUE THREAD

**Issue by peterTorrione** [covartech/PRT#69]
Clustering objects for the most part return un-sorted cluster centers, but this makes interpretation difficult.

For most clustering algorithms, there's no natural ordering of the data, but we can enforce a simple sorting, e.g., the first dim of the cluster centers are increasing.

If no complaints, I may implement in some clustering algorithms.

**Comment by kennethmorton** [comment]
I have no complaints. It's not always straight forward to resort the internals of specific clustering algorithms, but for many it should be relatively straight forward. This isn't something we can do automatically or something that we can assert that all clusters do, but we can do it as a best practice for commonly used clusters like k-means and a few others.

**Comment by peterTorrione** [comment]
This is implemented in https://github.com/covartech/PRT/commit/00db823c231fc454f6b71659338b4d35d425449e

for all the clustering algorithms we have that I can run (see the recent two issues #70 and #71 for details).

It works - 
<code>
%%
ds = prtDataGenBimodal;
ds = rt(prtPreProcZmuv,ds);
clusterers = {prtClusterDpMeans('lambda',1);
    prtClusterGmm;
    prtClusterKmeans;
%     prtClusterKmodes;
%     prtClusterMeanShift;
    prtClusterMeanShiftEuclidean;
    prtClusterSpectralKmeans;
    prtClusterSphericalKmeans;};

[mm,nn] = prtUtilGetSubplotDimensions(length(clusterers));

for cEnum = cvrEnumerate(clusterers)
    c{i} = cEnum.value.train(ds);
    
    subplot(nn,mm,cEnum.index)
    plot(c{i});
end
</code>

The clusters are in the right order - blue, red, green, along the 1st dimension

![clusterers_sorted](https://user-images.githubusercontent.com/1233805/40239539-559b107c-5a84-11e8-9ec4-ebd0b031173f.png)
